# https://taskfile.dev

version: '3'
tasks:
  build:
    cmds:
      - docker build -t dashboard:latest .
  push:
    cmds:
      - docker tag dashboard:latest mgnisia/dashboard:latest
      - docker push mgnisia/dashboard:latest
